### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by MaestroJurko** [Pixabay/jQuery-tinyDraggable#1]
I tested it on iOS Safari, it is not working.

How is the mobile support?

**Comment by SimonSteinberger** [comment]
Unfortunately I have no device to test Safari Mobile on. if anyone could try and confirm this - that would be great!

**Comment by PierBover** [comment]
It doesn't work on any mobile Browser. I've tried Chrome and Safari on iOS, and Chrome on Android.

Are you using touch events besides mouse events?

**Comment by SimonSteinberger** [comment]
No, touch events are not supported. It's supposed to be a very lightweight plugin and I believe, supporting touch events could get rather extensive. You could use jQuery UI's Draggable in combination with http://touchpunch.furf.com/
