### ISSUE TITLE
Request: Add class if dragged

### ISSUE THREAD

**Issue by flamez-b** [Pixabay/jQuery-tinyDraggable#3]
Thank you for the plugun, it is really smooth and fast!
Please help me to make a little option for my case:
I would like to add a class to the dragging div if it was moved from its initial place. Not a class while dragging, I mean a class only if the div was moved (dragged).

**Comment by SimonSteinberger** [comment]
Technically, it's no problem to include such a function. However, the main purpose of tinyDraggable is to have a really small draggable plugin for jQuery. Adding other options just makes it bigger - and there are several alternatives with a bunch of options available; e.g. jQuery UI draggable.

Maybe you can bind your own event handler to the objects in question, for example mousedown, mouseup or click events. In these callbacks you could additionally check the X/Y offset of the elements to see if they were moved.
