### ISSUE TITLE
Drag inside a div 

### ISSUE THREAD

**Issue by ManelHachani** [Pixabay/jQuery-tinyDraggable#6]
Hi thanks for this amazing plugin !
I have a problem ...
I want to drag an element inside a div ...the div container have this styles 
.container{
position:absolute;
top:50%;
left:50%;
transform:translate(-50%, -50%);
}
But when i test it ..the element disappear..and when i check the element styles i find:
position:relative;
top:-8263px;
left:10275px;

Oh ..yes ..i have to mention that the container div is in another div with also position: absolute , width:100% and height 100%.
so what to do ?
Thanks for your help in advance

**Comment by SimonSteinberger** [comment]
I'm not completely sure without testing it, but I think the draggable object cannot be placed inside any relative or absolute positioned container. You can take a look at the plugin code - it's really simple, you can very likely adapt it to your needs.
